apiVersion: v1
kind: Service
metadata:
  name: elastic-prod-sec-es-masters
  namespace: infra
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "elastic-prod-sec"
    elasticsearch.k8s.elastic.co/node-master: "true"
  type: LoadBalancer
