apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-europe-west3
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
